name: Deploy Node.js App to Heroku

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm install

      - name: Instalar CLI de Heroku
        uses: akhileshns/heroku-cli-action@v1.2.2
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "clientes-heroku-pulupa"
          heroku_email: "mftc2105@gmail.com"

      - name: Hacer deploy manual con Git
        run: |
          heroku git:remote -a clientes-heroku-pulupa
          git push https://heroku:$HEROKU_API_KEY@git.heroku.com/clientes-heroku-pulupa.git HEAD:main
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
